In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import normal
from matplotlib.widgets import Slider


In [64]:
class MyData:
    def __init__(self, yval, fmin, fmax, Np,
                 nRegions, xReg_min, xReg_max):
        self.nRegs = nRegions
        self.init_ox_oy(yval, fmin, fmax, Np,)
        self.init_funcs()
        self.val = 0

    def init_ox_oy(self, yval, fmin, fmax, Np,):
        self.ox = np.linspace(fmin, fmax, Np,)
        self.oy = np.full((len(self.ox)), yval) + \
            normal(scale=0.5, size=len(self.ox))
        self.reg_names = [f'r_{i}' for i in range(self.nRegs)]

    def init_funcs(self):
        self.funcs = []
        for i, fname in enumerate(self.reg_names):
            self.funcs.append(self.factory(fname,i))

    def factory(self,fname,dval):
        def f():
            print(fname, dval)
            self.val = self.val + dval
            print(self.val)
        return f


In [65]:
yval = -2
fmin = 20
fmax = 190
Np = 30
# ==== Define regions ====
nRegions = 3
xReg_min = 50
xReg_max = 105

b = MyData(yval, fmin, fmax, Np,
           nRegions, xReg_min, xReg_max)


In [66]:
print(b.val)
b.funcs[1]()

0
r_1 1
1


In [67]:
# Define factory
def factory(argument):
    def f():
        print(argument)
    return f


# Define functions
funcs = []
for i in range(10):
    funcs.append(factory(i))
# Run funcs
# for f in funcs:
#     f()


In [68]:
c = np.arange(5, 11, 1)
print(c)
np.put(c, [3,4], [20,22])
print(c)


[ 5  6  7  8  9 10]
[ 5  6  7 20 22 10]


In [71]:
a = np.array([-1,2,-3,5,6])
np.minimum(a, 0)


array([-1,  0, -3,  0,  0])